// Agent branding: the custom-emoji / unicode-emoji maps and model-name → base-key
// resolution (tg decomposition Stage 0, docs/specs/tg-decomposition.md). Pure data
// + a pure lookup; the `tg` entrypoint imports these instead of defining them
// inline. Behaviour is unchanged.
//
// WARNING: the structure of EMBEDDABLE_EMOJI_MAP is regex-parsed by
// tests/emoji_map.test.ts. If you change its formatting (nested braces, comments
// containing `}`, trailing commas), update that test in lockstep.
//
// Default: HyperIDE.ai custom emoji set (https://t.me/addemoji/agents_by_HyperIDE_Bot)
export const EMBEDDABLE_EMOJI_MAP: Record<string, string> = {
  hyperide: "5274191514178723918", // 🚁 HyperIDE
  codex: "5273797309195393626",   // 👐 OpenAI
  openai: "5273797309195393626",  // 👐 OpenAI
  claude: "5274170649227600531",  // ✳️ Claude
  anthropic: "5274170649227600531", // ✳️ Claude
  gemini: "5274254027427716477",  // ♊️ Gemini
  google: "5274254027427716477",  // ♊️ Gemini
  deepseek: "5274018976752511967", // 🐳 DeepSeek
  qwen: "5274109179655661197",    // 🟣 Qwen
  alibaba: "5274109179655661197", // 🟣 Qwen
  kimi: "5273889053991805596",    // 🌙 Kimi
  moonshot: "5273889053991805596", // 🌙 Kimi
  o3: "5273797309195393626",      // 👐 OpenAI
  o1: "5273797309195393626",      // 👐 OpenAI
  gpt4: "5273797309195393626",    // 👐 OpenAI
  gpt3: "5273797309195393626",    // 👐 OpenAI
  llama: "5274259902942977093",   // 🦙 Meta/llama
  meta: "5274259902942977093",    // 🦙 Meta
  ollama: "5273886056104634966",  // 🦙 Ollama
  mistral: "5273823740424134905", // Ⓜ️ Mistral
  grok: "5273973737861981852",    // 🤘 Grok
  xai: "5273973737861981852",     // 🤘 Grok
  copilot: "5274136375388580049", // 🦾 Copilot
  github: "5274136375388580049",   // 🦾 Copilot
  perplexity: "5273733846758631156", // 🔮 Perplexity
  cursor: "5273731871073672487",  // 👆 Cursor
  windsurf: "5273875761068025296", // 🏄 Windsurf
  devin: "5274170649227600531",   // Custom ID: shares Claude's ✳️ ID. Unicode: 🧑‍💻
  cognition: "5274170649227600531", // Custom ID: shares Claude's ✳️ ID. Unicode: 🧑‍💻
  aider: "5274170649227600531",    // Custom ID: shares Claude's ✳️ ID. Unicode: 🤝
  continue: "5274170649227600531", // Custom ID: shares Claude's ✳️ ID. Unicode: ⏩
  gpt: "5273797309195393626",       // Custom ID: shares OpenAI's 👐 ID. Unicode: ⚡
}

// Unicode emoji fallback map
export const UNICODE_EMOJI_MAP: Record<string, string> = {
  claude: "✳️", anthropic: "✳️",
  codex: "👐", openai: "👐", o3: "👐", o1: "👐", gpt4: "👐", gpt3: "👐", gpt: "⚡",
  gemini: "♊️", google: "♊️",
  deepseek: "🐳",
  qwen: "🟣", alibaba: "🟣",
  kimi: "🌙", moonshot: "🌙",
  glm: "🗂", chatglm: "🗂",
  llama: "🦙", meta: "🦙", ollama: "🦙",
  mistral: "Ⓜ️",
  grok: "🤘", xai: "🤘",
  copilot: "🦾", github: "🦾",
  perplexity: "🔮",
  cursor: "👆",
  windsurf: "🏄",
  devin: "🧑‍💻", cognition: "🧑‍💻",
  aider: "🤝",
  continue: "⏩",
  hyperide: "🚁",
  fireworks: "🎆",
}

// AI emoji mapping (plum11 convention + extended)
export const MODEL_EMOJI_MAP: Record<string, string> = {
  claude: "✳️", anthropic: "✳️",
  codex: "👐", openai: "👐", o3: "👐", o1: "👐", gpt4: "👐", gpt3: "👐",
  gemini: "♊️", google: "♊️",
  deepseek: "🐳",
  qwen: "🟣", alibaba: "🟣",
  kimi: "🌙", moonshot: "🌙",
  glm: "🗂", chatglm: "🗂",
  llama: "🦙", meta: "🦙", ollama: "🦙",
  mistral: "Ⓜ️",
  grok: "🤘", xai: "🤘",
  copilot: "🦾", github: "🦾",
  perplexity: "🔮",
  cursor: "👆",
  windsurf: "🏄",
  devin: "🧑‍💻", cognition: "🧑‍💻",
  aider: "🤝",
  continue: "⏩",
  hyperide: "🚁",
  fireworks: "🎆",
  gpt: "⚡",
}

// ---------------------------------------------------------------------------
// Tag pills (custom-emoji CHIPS for --tag). Each canonical (English) tag is a
// wordmark pill sliced into N square 100x100 custom-emoji cells; Telegram packs
// them edge-to-edge into one continuous chip. The cell assets live in
// emoji-icons/tags/<tag>_<i>.png (generated by scripts/build-tag-pills.py); the
// ids below come from uploading that set as a custom_emoji sticker set.
//
// The ids below are REAL Telegram custom_emoji_ids, harvested by
// scripts/create-tag-emoji.ts from the set replytags_by_hyperidebot
// (https://t.me/addemoji/replytags_by_hyperidebot), owned by @hyperidebot.
// NOTE: the SENDING bot (the configured TG_BOT_TOKEN, currently
// @UltraClaudeCodeBot) does NOT need to own this set — it can emit a
// custom_emoji entity that references a set owned by a different bot
// (verified live: sendMessage with these ids returns ok=true through the
// sending bot). Re-run the create script with @hyperidebot's token and
// re-wire these ids if the pills are regenerated.
//
// The renderer (features/render/prefix.ts) gates on hasRealPillIds(): a tag
// whose ids are still the literal "PLACEHOLDER" string falls back to the
// unicode TAG_PILL_FALLBACK badge — a placeholder must NEVER go out inside a
// <tg-emoji> tag (Telegram rejects it with ENTITY_TEXT_INVALID).
//
// Order matters: the ids are the LEFT->RIGHT cell order (<tag>_0, <tag>_1, ...),
// rendered in that order so the chip re-stitches correctly.
export const TAG_PILL_PLACEHOLDER = "PLACEHOLDER"

export const TAG_PILL_IDS: Record<string, string[]> = {
  ANSWER: ["5294303944082762041", "5294414440706382789", "5294185480294808567"],   // answer_0..2
  DECISION: ["5294395852087926650", "5294110472985944747", "5294433613440395921"], // decision_0..2
  PROBLEM: ["5294376430245817725", "5294542383487164540", "5294432754446935044"],  // problem_0..2
  // QUESTION has NO dedicated pill asset (none was uploaded). Deliberately
  // PLACEHOLDER, not a reuse of DECISION's real ids: reusing them would make
  // hasRealPillIds('QUESTION') true, so a premium client would render a
  // DECISION-labeled wordmark pill for --tag question while a non-premium
  // client sees the correct "🟠 QUESTION" unicode fallback — a visible
  // mismatch (review finding). Placeholder keeps EVERY viewer on the
  // consistent unicode fallback until a real QUESTION pill is uploaded
  // (scripts/create-tag-emoji.ts) and these three ids are filled in.
  QUESTION: [TAG_PILL_PLACEHOLDER, TAG_PILL_PLACEHOLDER, TAG_PILL_PLACEHOLDER],
  REPORT: ["5294525981007062296", "5294382683718200108", "5294436190420770975"],   // report_0..2
}

// The colored DOT per canonical tag (single emoji). The leading glyph of
// TAG_PILL_FALLBACK and the FIRST pill cell's per-cell fallback (see
// tagPillCellDots). Each color tells you WHICH tag at a glance.
export const TAG_PILL_DOT: Record<string, string> = {
  ANSWER: "🔵",
  DECISION: "🟠",
  PROBLEM: "🔴",
  QUESTION: "🟠", // shares DECISION's color — see TAG_PILL_IDS above
  REPORT: "🟢",
}

// The neutral dot used for every pill cell AFTER the first one. A quiet
// white-square so a push notification (rendered by the OS, not Telegram — it
// can't load the custom-emoji image) shows ONE colored dot + N-1 neutrals
// (e.g. "🔵▫️▫️") instead of N loud identical color dots.
// (CTO 2026-06-15: color cell0 identifies the tag, the rest stay neutral.)
export const TAG_PILL_NEUTRAL_DOT = "▫️"

// Build a pill's per-cell dot list for an EXPLICIT cell count: cell 0 = the
// colored dot, cells 1..n-1 = the neutral square. Pure (no TAG_PILL_IDS lookup),
// so the upload script can pass its own generated cell count without drifting
// from the live ids.
export function cellDotsFor(colorDot: string, cellCount: number): string[] {
  if (!colorDot || cellCount <= 0) return []
  return [colorDot, ...Array.from({ length: cellCount - 1 }, () => TAG_PILL_NEUTRAL_DOT)]
}

// The per-CELL inner fallback for each canonical tag's pill: cell 0 keeps the
// tag's colored dot, cells 1..n-1 are the neutral square. The cell count comes
// from TAG_PILL_IDS (the uploaded set's cell layout), so this stays in lockstep
// with the real sticker cells. The inner text of each <tg-emoji> cell MUST equal
// that cell's Telegram-side alt (emoji_list) or Telegram drops the entity, so
// the alts on the live set are kept in sync (scripts/sync-tag-pill-alts.ts).
export function tagPillCellDots(canonicalTag: string): string[] {
  return cellDotsFor(TAG_PILL_DOT[canonicalTag] ?? "", TAG_PILL_IDS[canonicalTag]?.length ?? 0)
}

// Unicode fallback shown to non-premium viewers and whenever the pill ids are
// still placeholders: a colored dot + the English word. Colors mirror the pill
// fills in scripts/build-tag-pills.py (blue / amber / red / green).
export const TAG_PILL_FALLBACK: Record<string, string> = {
  ANSWER: "🔵 ANSWER",
  DECISION: "🟠 DECISION",
  PROBLEM: "🔴 PROBLEM",
  QUESTION: "🟠 QUESTION",
  REPORT: "🟢 REPORT",
}

// True when EVERY id for a tag is a real Telegram custom_emoji_id (a long
// numeric string), i.e. the set has been uploaded and TAG_PILL_IDS filled. A
// missing entry, an empty list, or any placeholder/non-numeric id makes this
// false -> the renderer uses the unicode fallback instead of a broken tg-emoji.
export function hasRealPillIds(canonicalTag: string): boolean {
  const ids = TAG_PILL_IDS[canonicalTag]
  if (!ids || ids.length === 0) return false
  return ids.every((id) => /^\d{15,}$/.test(id))
}

// A custom-emoji entity on the outbound text (Telegram messageEntityCustomEmoji):
// offset/length are UTF-16 positions into the rendered text.
export interface EmojiEntity {
  type: "custom_emoji"
  offset: number
  length: number
  custom_emoji_id: string
}

export interface ParsedText {
  text: string
  entities: EmojiEntity[]
}

// Resolve a model name to its emoji-map base key: exact match, then progressively
// shorter "-"/"_"-split prefixes (e.g. "claude-opus-4" → "claude"). Falls back to
// the lowercased name when nothing matches.
export function extractBaseModel(modelName: string): string {
  const lower = modelName.toLowerCase()
  if (MODEL_EMOJI_MAP[lower]) return lower
  if (EMBEDDABLE_EMOJI_MAP[lower]) return lower
  const parts = lower.split(/[-_]/)
  for (let i = parts.length; i > 0; i--) {
    const prefix = parts.slice(0, i).join("-")
    if (MODEL_EMOJI_MAP[prefix]) return prefix
    if (EMBEDDABLE_EMOJI_MAP[prefix]) return prefix
  }
  return lower
}
