#!/usr/bin/env bun
/**
 * Create the Telegram custom-emoji sticker set for the message-tag PILLS.
 *
 * Each canonical (English) tag — ANSWER / DECISION / PROBLEM / REPORT — is a
 * wordmark pill sliced into N square 100x100 cells (emoji-icons/tags/<tag>_<i>.png,
 * generated by scripts/build-tag-pills.py). Every cell is uploaded as one custom
 * emoji; Telegram packs them edge-to-edge so the N cells re-stitch into one chip.
 *
 * Prerequisites:
 *   - Generate the cells first:  python3 scripts/build-tag-pills.py
 *   - Set TG_BOT_TOKEN and TG_OWNER_ID env vars
 *   - Run: bun scripts/create-tag-emoji.ts [--dry-run]
 *
 * The script auto-detects the bot username and creates a set named:
 *   replytags_by_<bot_username>   (sticker_type=custom_emoji)
 *
 * After creation it harvests the per-cell custom_emoji_ids (in cell order) into
 * a TAG_PILL_IDS-shaped object and prints it; paste that into
 * features/branding/emoji.ts (replacing the PLACEHOLDER ids).
 *
 * Mirrors scripts/create-ai-emoji-set.ts; the only differences are the asset
 * layout (multiple cells per tag) and the harvest shape (string[] per tag).
 */

import { existsSync } from 'fs';
import { join } from 'path';

// MUST stay in sync with the TAGS dict in build-tag-pills.py, TAG_PILL_IDS in
// features/branding/emoji.ts, and the TAG_ALIASES canonicals in
// features/render/tag.ts. Key = canonical (English) tag word; `cells` = how
// many 100px cells the pill was sliced into; `stem` = the file stem (lowercase).
// `emoji` = the unicode glyph attached to each cell as the custom emoji's
// emoji_list entry (a colored dot mirroring the pill fill; non-premium clients
// show this).
const TAG_PILLS: Record<string, { stem: string; cells: number; emoji: string }> = {
  ANSWER: { stem: 'answer', cells: 2, emoji: '🔵' },
  DECISION: { stem: 'decision', cells: 3, emoji: '🟠' },
  PROBLEM: { stem: 'problem', cells: 3, emoji: '🔴' },
  REPORT: { stem: 'report', cells: 2, emoji: '🟢' },
};

const SET_NAME = 'replytags';
const SET_TITLE = 'HyperIDE.ai · Reply Tags';
const IMAGE_DIR = join(import.meta.dir, '..', 'emoji-icons', 'tags');

interface Args {
  dryRun: boolean;
}

function parseArgs(): Args {
  return { dryRun: process.argv.slice(2).includes('--dry-run') };
}

async function getBotUsername(token: string): Promise<string> {
  const resp = await fetch(`https://api.telegram.org/bot${token}/getMe`);
  const data = (await resp.json()) as {
    ok: boolean;
    result?: { username: string };
    description?: string;
  };
  if (!data.ok) throw new Error(`getMe failed: ${data.description ?? 'unknown'}`);
  return data.result!.username;
}

// Flatten the per-tag cells into the ordered upload list. Each entry is one
// custom emoji (one pill cell). `tag`/`idx` let us re-group the harvested ids
// back per tag, in cell order, after upload.
interface CellEntry {
  tag: string;
  idx: number;
  file: string;
  emoji: string;
}

function buildCellEntries(): CellEntry[] {
  const entries: CellEntry[] = [];
  for (const [tag, pill] of Object.entries(TAG_PILLS)) {
    for (let i = 0; i < pill.cells; i++) {
      entries.push({
        tag,
        idx: i,
        file: join(IMAGE_DIR, `${pill.stem}_${i}.png`),
        emoji: pill.emoji,
      });
    }
  }
  return entries;
}

async function createSet(token: string, ownerId: number, dryRun: boolean): Promise<void> {
  const botUsername = await getBotUsername(token);
  const setName = `${SET_NAME}_by_${botUsername}`;

  const cells = buildCellEntries();

  // Preflight: every configured cell MUST have an image. A partial upload would
  // create a broken set that still looks successful, so fail first.
  const missing = cells.filter((c) => !existsSync(c.file)).map((c) => c.file);

  if (dryRun) {
    console.log(`[DRY RUN] Would create set: ${setName} (${cells.length} cells)`);
    for (const c of cells) {
      const status = existsSync(c.file) ? '' : ' (MISSING)';
      console.log(`  - ${c.tag}[${c.idx}]: ${c.emoji} (${c.file})${status}`);
    }
    if (missing.length) {
      console.log(`[DRY RUN] ${missing.length} image(s) missing: ${missing.join(', ')}`);
    }
    return;
  }

  if (missing.length) {
    console.error(`Error: missing cell image(s) for: ${missing.join(', ')}`);
    console.error(`Generate them first: python3 scripts/build-tag-pills.py`);
    process.exit(1);
  }

  // Bot API 6.6+ createNewStickerSet: pass `stickers` as a JSON array of
  // InputSticker objects, each referencing an attached file via attach://.
  // Up to 50 stickers per call, so create the whole set in one request.
  const form = new FormData();
  form.append('user_id', String(ownerId));
  form.append('name', setName);
  form.append('title', SET_TITLE);
  form.append('sticker_type', 'custom_emoji');
  const inputStickers = cells.map((c, idx) => {
    const attach = `file${idx}`;
    form.append(attach, Bun.file(c.file));
    return { sticker: `attach://${attach}`, format: 'static', emoji_list: [c.emoji] };
  });
  form.append('stickers', JSON.stringify(inputStickers));

  const resp = await fetch(`https://api.telegram.org/bot${token}/createNewStickerSet`, {
    method: 'POST',
    body: form,
  });
  const result = (await resp.json()) as { ok: boolean; description?: string };
  if (!result.ok) {
    console.error(`Error creating set: ${result.description ?? 'unknown'}`);
    process.exit(1);
  }

  console.log(`Created set: ${setName} (${cells.length} cells)`);

  // Fetch the finished set and harvest custom_emoji_ids. Stickers come back in
  // insertion order (matches `cells`); zip by index and re-group per tag in
  // cell order to build the TAG_PILL_IDS shape.
  const infoResp = await fetch(`https://api.telegram.org/bot${token}/getStickerSet?name=${setName}`);
  const info = (await infoResp.json()) as {
    ok: boolean;
    result?: { stickers: Array<{ custom_emoji_id?: string }> };
  };
  if (!info.ok || !info.result) {
    console.warn(`Warning: could not fetch set for IDs`);
    return;
  }

  const mapping: Record<string, string[]> = {};
  cells.forEach((c, idx) => {
    const cid = info.result!.stickers[idx]?.custom_emoji_id ?? '';
    (mapping[c.tag] ??= [])[c.idx] = cid;
  });

  console.log(`\nSet URL: https://t.me/addemoji/${setName}\n\nTAG_PILL_IDS:`);
  console.log(JSON.stringify(mapping, null, 2));
  console.log(`\nPaste the above into features/branding/emoji.ts (TAG_PILL_IDS), replacing the PLACEHOLDER ids.`);
}

async function main() {
  const { dryRun } = parseArgs();
  const token = process.env.TG_BOT_TOKEN;
  const ownerId = process.env.TG_OWNER_ID ? parseInt(process.env.TG_OWNER_ID, 10) : 0;

  if (!token) {
    console.error('Error: Set TG_BOT_TOKEN env var');
    process.exit(1);
  }
  if (!ownerId) {
    console.error('Error: Set TG_OWNER_ID env var to your Telegram numeric user ID');
    process.exit(1);
  }

  await createSet(token, ownerId, dryRun);
}

main();
